- hosts: all
  become: yes
  vars:
    service: "{{ service }}"
  tasks:
    - name: Define port per service
      set_fact:
        host_port: >-
          {% if service == 'service1' %}
            8081
          {% elif service == 'service2' %}
            8082
          {% else %}
            9999
          {% endif %}
        container_port: >-
          {% if service == 'service1' %}
            80
          {% elif service == 'service2' %}
            3000
          {% else %}
            80
          {% endif %}

    - name: Run Docker container
      docker_container:
        name: "{{ service }}"
        image: "edensit139/{{ service }}:latest"
        state: started
        ports:
          - "{{ host_port }}:{{ container_port }}"
