- hosts: all
  become: yes
  vars:
    service: "{{ service_name }}"
  tasks:
    - name: Define ports based on service
      set_fact:
        host_port: "{{ '80' if service == 'service-nginx' else '3000' if service == 'service-node' else '9999' }}"
        container_port: "{{ '80' if service == 'service-nginx' else '3000' if service == 'service-node' else '80' }}"

    - name: Run Docker container
      docker_container:
        name: "{{ service }}"
        image: "<your-docker-hub-username>/{{ service }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ host_port }}:{{ container_port }}"